name: "Regenerate PluginMaster"

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/regenerate.yaml"
      - "generate_pluginmaster.py"
      - "plugins/**"
  schedule:
    - cron: '0 */12 * * *'

concurrency: "regenerate"

permissions:
  contents: "write"

jobs:
  generate:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7

      - name: "Install uv"
        uses: "astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b" # v8
        with:
          version: "0.11.32"

      - name: "Generate PluginMaster"
        run: "uv run generate_pluginmaster.py"

      - name: "Commit PluginMaster"
        uses: "EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321" # v10
        with:
          author_name: "GitHub Action"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "Regenerate PluginMaster"
